version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-net
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - db-net
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

networks:
  db-net:
    driver: bridge

volumes:
  db-data:
